Iz dev
NonameUntitled/GSRec pull request #3
Opened 2024-01-14 22:32 UTC by preskes

2024-02-19 01:05 UTC, NonameUntitled requested changes

2024-02-19 01:05 UTC, NonameUntitled commented on modeling/infer.py
> +		experiment_name = output_params['experiment_name'].replace('light_gcn','lightgcn')
It looks like a bad solution, we may have different models with underscores. you can take a model name from `type` field inside `model` config part if you want.

2024-02-19 01:05 UTC, NonameUntitled commented on modeling/infer.py
> +            'dataset': experiment_name.split('_')[1],
Bad solution, the experiment name can be completely random, here you add additional constraints without any explanation provided.

2024-02-19 01:05 UTC, NonameUntitled commented on modeling/infer.py
> +    if output_path:
`if output_path is not None:`

2024-02-19 01:05 UTC, NonameUntitled commented on modeling/infer.py
> +            line[metric_name] = round(np.mean(metric_value), 18)
18 digits is extremely precise, I think 4-6 digits is more than enough.

2024-02-19 01:05 UTC, NonameUntitled commented on modeling/infer.py
> +            output_file.write('{}\n'.format(json.dumps(line)))
It looks like print json dump would be very difficult to read, maybe use tsv format?
It is easier to read by eyes and you can read metrics with pandas as well.

2024-02-19 01:05 UTC, NonameUntitled commented on modeling/infer.py
> +            'experiment_name': output_params['experiment_name'],
In case of `output_params = None` it will fail with an error.

2024-02-19 01:05 UTC, NonameUntitled commented on modeling/infer.py
> +    if output_path:
I think this `if` statement is redundant, no one will die if you save this file unexpectedly.

2024-02-19 01:05 UTC, NonameUntitled commented on modeling/infer.py
> +    #TODO implement output_path as argument in utils.parse_args
I think it is not needed, I don't think anyone will use different files for metrics.

2024-02-19 01:05 UTC, NonameUntitled commented on modeling/train.py
> +    step_threshold = 20000
It i better to not use it by default. Let's re-write it to use only in specific cases.

2024-02-19 01:05 UTC, NonameUntitled commented on notebooks/AliAdDatasetPreprocessor.ipynb
???

2024-02-19 01:05 UTC, NonameUntitled commented on modeling/models/gtorec.py
> +            score_function='cos', # способ вычисления скора для айтема: 'cos' или 'dot'
Давай по дефолту просто делать скалярное произведение, не надо пока никакого косинуса

2024-02-19 01:05 UTC, NonameUntitled commented on modeling/models/gtorec.py
> +            layer_norm_eps=1e-9, # Q: общее значение для seq и graph?
Да, это общее значение дял модели, пока что нет смысла разделять

2024-02-19 01:05 UTC, NonameUntitled commented on modeling/models/gtorec.py
> +            initializer_range=0.02, # Q: общее значение для seq и graph?
Да, это общее значение для модели

2024-02-19 01:05 UTC, NonameUntitled commented on modeling/models/gtorec.py
> +            other_domains, # Q: нужно ли это здесь?
Пока не вижу смысла в этой переменной, так как у нас только 2 домена. Вместо неё можешь добавить поле `source_domain` по которму доставать потом в `forward` поля домена

2024-02-19 01:05 UTC, NonameUntitled commented on modeling/models/gtorec.py
> +            positive_prefix, # Q: общий параметр для seq и graph?
Давай пока одни и теже негативы семплить, да, потом можно будет поменять при желании

2024-02-19 01:05 UTC, NonameUntitled commented on modeling/models/gtorec.py
> +            is_causal=True # false for bert4rec # Q: за что отвечает данный параметр и какое значение нужно?
Каузальная маска при использовании трансформера. Необходимость определяется путем того, как ты хочешь учить модель/на какой лосс.

2024-02-19 01:05 UTC, NonameUntitled commented on modeling/models/gtorec.py
> +        self._graph_user_prefix = user_prefix # Q: получаем из create_from_config?
Я не виэу смысла в дублировании того, то уже есть.

2024-02-19 01:05 UTC, NonameUntitled commented on modeling/models/gtorec.py
> +        self._graph_num_users = num_users # Q: откуда взять?
Ну у тебя количество пользователей и айтемов одни и тоже вне зависимости от наличия графа или отсутствия

2024-02-19 01:05 UTC, NonameUntitled commented on modeling/models/gtorec.py
> +        self._graph_embedding_dim = graph_embedding_dim # Q: нужна отдельная переменная или достаточно той, что у трансформера?
Не вижу смысла делать отдельную переменную

2024-02-19 01:05 UTC, NonameUntitled commented on modeling/models/gtorec.py
> +    def _init_graph_weights(self, initializer_range):
Можешь удалить эту функцию, там в `TorchModel` уже есть норм реализация

2024-02-19 01:05 UTC, NonameUntitled commented on modeling/models/gtorec.py
> +    def _apply_graph_encoder(self):
Синканись с новым кодом, там я немного эту логику изменил

2024-02-19 01:05 UTC, NonameUntitled commented on modeling/models/gtorec.py
> +        # Q: ???
???

2024-02-19 01:05 UTC, NonameUntitled commented on modeling/models/gtorec.py
> +            # TODO # Q: ???
???

2024-02-19 01:05 UTC, NonameUntitled commented on modeling/models/gtorec.py
> +            if self._use_ce:
Убери `use_ce`, нам это не нужно пока

2024-02-19 01:05 UTC, NonameUntitled commented on modeling/models/gtorec.py
> +class GTOModel(SequentialTorchModel, config_name='gtorec'):
Просто интересно, почему GTO?

2024-02-19 01:05 UTC, NonameUntitled commented on modeling/models/gtorec.py
> +        )
В конце фнукции хорошо бы веса инифиализировать

2024-02-19 01:05 UTC, NonameUntitled commented on modeling/models/gtorec.py
> +        self._init_graph_weights(initializer_range)
А это лучше не здесь делать

2024-02-19 01:05 UTC, NonameUntitled commented on modeling/models/gtorec.py
> +        self._use_ce = use_ce # from sasrec # Q: нужно или удалить?
Пока это не надо

2024-02-19 01:05 UTC, NonameUntitled commented on modeling/models/gtorec.py
> +        self._init_weights(initializer_range)
А почему у тебя это дублируется?

2024-02-19 01:05 UTC, NonameUntitled commented on modeling/models/gtorec.py
> +        self.norm_first = norm_first # Q: откуда взять?
Добавить в параметры `create_from_config`

2024-02-19 01:05 UTC, NonameUntitled commented on modeling/models/gtorec.py
> +        # Q: как получить разные выходы графовой модели (оранжевый_2 и синий_2 на рисунке) ?
Семплировать по разным user_id (source и target)

2024-02-19 01:05 UTC, NonameUntitled commented on modeling/models/gtorec.py
> +            # TODO # Q: ???
???

2024-02-19 01:05 UTC, NonameUntitled commented on modeling/models/gtorec.py
> +            if self._use_ce:
CE не нужно

2024-02-19 01:05 UTC, NonameUntitled commented on modeling/models/gtorec.py
> +                # Q: возвращаем только эмбеды, без скоров? как вычислять bpr-loss без скоров?
Ну в целом ты можешь скоры тут посчитать как в реализации light gcn сейчас сделано

2024-02-19 01:05 UTC, NonameUntitled commented on modeling/models/gtorec.py
> +                        last_embeddings,
Ну вот брать `lest_embeddings` кажется что не оч идея конечно, лучше сделать какой-то пуллинг представлений хотя бы

2024-02-19 01:05 UTC, NonameUntitled commented on modeling/infer_multiple.py
This file is not needed. There are too many problems with it, let's discuss it during the meeting

2024-02-21 22:14 UTC, preskes commented on modeling/infer.py
> +		experiment_name = output_params['experiment_name'].replace('light_gcn','lightgcn')
fixed

2024-02-21 22:14 UTC, preskes commented on modeling/infer.py
> +            'dataset': experiment_name.split('_')[1],
fixed

2024-02-21 22:14 UTC, preskes commented on modeling/infer.py
> +    if output_path:
fixed

2024-02-21 22:15 UTC, preskes commented on modeling/infer.py
> +            line[metric_name] = round(np.mean(metric_value), 18)
fixed. set to 8, because some experiment end with values lower than 10e-3

2024-02-21 22:16 UTC, preskes commented on modeling/infer.py
> +            output_file.write('{}\n'.format(json.dumps(line)))
fixed

2024-02-21 22:19 UTC, preskes commented on modeling/infer.py
> +            'experiment_name': output_params['experiment_name'],
fixed

2024-02-21 22:19 UTC, preskes commented on modeling/infer.py
> +    if output_path:
fixed

2024-02-21 22:20 UTC, preskes commented on modeling/infer.py
> +    #TODO implement output_path as argument in utils.parse_args
fixed

2024-02-21 22:20 UTC, preskes commented on modeling/train.py
> +    step_threshold = 20000
fixed

2024-02-21 22:20 UTC, preskes commented on notebooks/AliAdDatasetPreprocessor.ipynb
file was renamed

2024-02-21 22:20 UTC, preskes commented on modeling/models/gtorec.py
> +            score_function='cos', # способ вычисления скора для айтема: 'cos' или 'dot'
fixed

2024-02-21 22:20 UTC, preskes commented on modeling/models/gtorec.py
> +            layer_norm_eps=1e-9, # Q: общее значение для seq и graph?
fixed

2024-02-21 22:21 UTC, preskes commented on modeling/models/gtorec.py
> +            initializer_range=0.02, # Q: общее значение для seq и graph?
fixed

2024-02-21 22:21 UTC, preskes commented on modeling/models/gtorec.py
> +            other_domains, # Q: нужно ли это здесь?
fixed

2024-02-21 22:21 UTC, preskes commented on modeling/models/gtorec.py
> +            positive_prefix, # Q: общий параметр для seq и graph?
fixed

2024-02-21 22:21 UTC, preskes commented on modeling/models/gtorec.py
> +            is_causal=True # false for bert4rec # Q: за что отвечает данный параметр и какое значение нужно?
fixed

2024-02-21 22:21 UTC, preskes commented on modeling/models/gtorec.py
> +        self._graph_user_prefix = user_prefix # Q: получаем из create_from_config?
fixed

2024-02-21 22:21 UTC, preskes commented on modeling/models/gtorec.py
> +        self._graph_num_users = num_users # Q: откуда взять?
fixed

2024-02-21 22:23 UTC, preskes commented on modeling/models/gtorec.py
> +        self._graph_embedding_dim = graph_embedding_dim # Q: нужна отдельная переменная или достаточно той, что у трансформера?
fixed. kept parameter as we discussed

2024-02-21 22:24 UTC, preskes commented on modeling/models/gtorec.py
> +        # Q: ???
fixed

2024-02-21 22:36 UTC, preskes commented on modeling/models/gtorec.py
> +            if self._use_ce:
fixed

2024-02-21 22:36 UTC, preskes commented on modeling/models/gtorec.py
> +class GTOModel(SequentialTorchModel, config_name='gtorec'):
**G**raph**T**ransf**O**rmerModel

2024-02-21 22:37 UTC, preskes commented on modeling/models/gtorec.py
> +        )
fixed

2024-02-21 22:37 UTC, preskes commented on modeling/models/gtorec.py
> +        self._init_graph_weights(initializer_range)
fixed

2024-02-21 22:37 UTC, preskes commented on modeling/models/gtorec.py
> +        self._use_ce = use_ce # from sasrec # Q: нужно или удалить?
fixed

2024-02-21 22:37 UTC, preskes commented on modeling/models/gtorec.py
> +        self._init_weights(initializer_range)
fixed

2024-02-21 22:38 UTC, preskes commented on modeling/models/gtorec.py
> +        self.norm_first = norm_first # Q: откуда взять?
fixed

2024-02-21 22:38 UTC, preskes commented on modeling/models/gtorec.py
> +            if self._use_ce:
fixed

2024-02-21 22:47 UTC, preskes commented on modeling/models/gtorec.py
> +            # TODO # Q: ???
fixed

2024-02-21 22:47 UTC, preskes commented on modeling/models/gtorec.py
> +    def _apply_graph_encoder(self):
fixed

2024-02-21 22:47 UTC, preskes commented on modeling/models/gtorec.py
> +    def _init_graph_weights(self, initializer_range):
fixed

2024-02-21 22:47 UTC, preskes commented on modeling/models/gtorec.py
> +            # TODO # Q: ???
fixed

2024-02-21 22:48 UTC, preskes commented on modeling/models/gtorec.py
> +                # Q: возвращаем только эмбеды, без скоров? как вычислять bpr-loss без скоров?
fixed

2024-02-21 23:32 UTC, preskes commented on modeling/infer_multiple.py
fixed

2024-02-21 23:49 UTC, preskes commented on modeling/models/gtorec.py
> +        # Q: как получить разные выходы графовой модели (оранжевый_2 и синий_2 на рисунке) ?
fixed

2024-02-22 00:44 UTC, preskes commented on modeling/models/gtorec.py
> +                        last_embeddings,
what exactly pooling is required? 
I suppose element-wise torch.max of 3 last_embeddings, because it keeps tensors' size

2024-02-26 07:39 UTC, NonameUntitled requested changes

2024-02-26 07:39 UTC, NonameUntitled commented on modeling/infer.py
> +    if not(output_path is None):
`if output_path is not None:`

2024-02-26 07:39 UTC, NonameUntitled commented on modeling/infer.py
> +        if not(output_params is None):
`if output_params is not None:`

2024-02-26 07:39 UTC, NonameUntitled commented on modeling/infer.py
> +            for param_name, param_value in output_params.items():
`line.update(output_params)`

2024-02-26 07:39 UTC, NonameUntitled commented on modeling/infer.py
> +    if config['dataset'].get('dataset', None) is None:
`if 'dataset' not in config['dataset']:`

2024-02-26 07:39 UTC, NonameUntitled commented on modeling/infer.py
> +        output_params['domain'] = config['dataset'].get('target_domain', config['dataset']['name'].split('/')[1])
```
if 'target_domain' in config['dataset']: 
  output_params['domain'] = config['dataset']['target_domain']
```

2024-02-26 07:39 UTC, NonameUntitled commented on modeling/infer.py
> +        output_params['domain'] = config['dataset']['dataset'].get('target_domain', config['dataset']['dataset']['name'].split('/')[1])
The same as above

2024-02-26 07:39 UTC, NonameUntitled commented on modeling/models/gtorec.py
> +    def _apply_graph_encoder(self):
не fixed, у тебя eval mode неправильно написан

2024-02-26 07:39 UTC, NonameUntitled commented on modeling/models/gtorec.py
> +        graph_item_embeddings_target = graph_embeddings_target[graph_item_mask_target]  # (batch_size, embedding_dim)
Не та размерность написана

2024-02-26 07:39 UTC, NonameUntitled commented on modeling/models/gtorec.py
> +        graph_item_embeddings_source = graph_embeddings_source[graph_item_mask_source]  # (batch_size, embedding_dim)
Не та размерность написана

2024-02-26 07:39 UTC, NonameUntitled commented on modeling/models/gtorec.py
> +            ))  # (batch_size, seq_len, embedding_dim)
Хорошо бы в комментах к коду как-то разделять где source seq len а где target seq len

2024-02-26 07:39 UTC, NonameUntitled commented on modeling/models/gtorec.py
> +        mha_embeddings_target = self._mha_output_projection(mha_embeddings_target)  # (batch_size, seq_len, embedding_dim)
Так как мы вроде бы ниже не используем больше mha_embeddings_target, то по идее можно местами поменять get_last_embedding и mha_output_projection если ты как-то планируешь mha_embeddings_target дальше использовать, то менять не надо

2024-02-26 07:39 UTC, NonameUntitled commented on modeling/train.py
>          epoch_cnt=config.get('train_epochs_num', None),
`config.get('train_epochs_num')` will return None by default, let's fix it everywhere

2024-02-26 08:37 UTC, preskes commented on modeling/train.py
>          epoch_cnt=config.get('train_epochs_num', None),
fixed

2024-02-26 08:45 UTC, preskes commented on modeling/infer.py
> +    if not(output_path is None):
fixed

2024-02-26 08:46 UTC, preskes commented on modeling/infer.py
> +        if not(output_params is None):
fixed

2024-02-26 08:51 UTC, preskes commented on modeling/infer.py
> +            for param_name, param_value in output_params.items():
fixed

2024-02-26 08:52 UTC, preskes commented on modeling/infer.py
> +    if config['dataset'].get('dataset', None) is None:
fixed

2024-02-26 08:52 UTC, preskes commented on modeling/infer.py
> +        output_params['domain'] = config['dataset'].get('target_domain', config['dataset']['name'].split('/')[1])
fixed

2024-02-26 08:52 UTC, preskes commented on modeling/infer.py
> +        output_params['domain'] = config['dataset']['dataset'].get('target_domain', config['dataset']['dataset']['name'].split('/')[1])
fixed

2024-02-26 09:00 UTC, preskes commented on modeling/models/gtorec.py
> +        graph_item_embeddings_source = graph_embeddings_source[graph_item_mask_source]  # (batch_size, embedding_dim)
fixed

2024-02-26 09:01 UTC, preskes commented on modeling/models/gtorec.py
> +        graph_item_embeddings_target = graph_embeddings_target[graph_item_mask_target]  # (batch_size, embedding_dim)
fixed

2024-02-26 09:12 UTC, preskes commented on modeling/models/gtorec.py
> +        mha_embeddings_target = self._mha_output_projection(mha_embeddings_target)  # (batch_size, seq_len, embedding_dim)
Let's discuss at the meeting

2024-02-26 09:12 UTC, preskes commented on modeling/models/gtorec.py
> +            ))  # (batch_size, seq_len, embedding_dim)
Let's discuss at the meeting

2024-03-04 00:10 UTC, NonameUntitled approved these changes

2024-03-06 02:07 UTC, NonameUntitled approved these changes

2024-03-06 10:58 UTC, preskes commented
#changes
- gtorec model implementation and related configs added
- metrics logging added
- step-based stopping criterion added
- useless configs deleted
- some bugs fixed

2024-03-06 11:00 UTC, merged