Bert4rec, make it use sequence dataset with last iten prediction sampler, add loss batch_logsoftmax
NonameUntitled/GSRec pull request #6
Opened 2024-09-08 18:00 UTC by YaroslavZhurba

2024-09-08 18:04 UTC, YaroslavZhurba commented on modeling/models/bert4rec.py
> +            candidate_prefix,
я давно не делал pull master и так много всего изменилось, вернул для совместимости

2024-09-08 18:05 UTC, YaroslavZhurba commented on modeling/models/bert4rec.py
> +        self._cls_token = nn.Parameter(torch.rand(1, 1, embedding_dim))
здесь заменил на rand, по идее сейчас создается вектор от 0 до 1 с рандомными значениями

2024-09-08 18:06 UTC, YaroslavZhurba commented on modeling/models/bert4rec.py
> +            if '{}.ids'.format(self._candidate_prefix) in inputs: # only validation should be here
это похоже, сейчас вообще работать не будет. Я обновил свой код сделава пул мастера и смерджив его и почему-то массово пропали все валидационные семплеры, не понял что произошло, код пока оставил

2024-09-09 13:51 UTC, NonameUntitled requested changes

2024-09-09 13:51 UTC, NonameUntitled commented on configs/train/bert4rec_train_config.json
> -    "type": "scientific",
Конфиги надо не менять, а сделать новые с пометкой, что это bert4rec_new или что-то в этом роде

2024-09-09 13:51 UTC, NonameUntitled commented on modeling/loss/base.py
> +        return cls(predictions_prefix=config.get('predictions_prefix'), candidates_prefix=config.get('candidates_prefix'))
Тут надо разнести по разным строчкам `predictions_prefix` и `candidates_prefix`, чтобы проще читалось

2024-09-09 13:51 UTC, NonameUntitled commented on modeling/loss/base.py
> +        softmax_matrix = F.softmax(dot_product_matrix, dim=1)
Ты говорил, что эту часть нормально перепишешь с использованием [вот этого](https://pytorch.org/docs/stable/generated/torch.nn.LogSoftmax.html)

2024-09-09 13:51 UTC, NonameUntitled commented on modeling/models/base.py
> +    def _apply_sequential_encoder(self, events, lengths, add_cls_token = False):
```suggestion
    def _apply_sequential_encoder(self, events, lengths, add_cls_token=False):
```

2024-09-09 13:51 UTC, NonameUntitled commented on modeling/models/base.py
> +
Лишняя пустая строка

2024-09-09 13:51 UTC, NonameUntitled commented on modeling/models/base.py
> +            cls_token_expanded = self._cls_token.expand(batch_size, -1, -1) # !!! use torch tile
А комментарий `# !!! use torch tile` это просто шутка?)

2024-09-09 13:51 UTC, NonameUntitled commented on modeling/models/bert4rec.py
> +        self._cls_token = nn.Parameter(torch.rand(1, 1, embedding_dim))
Потом не забудь заменить на нормальную размерность

2024-09-09 13:51 UTC, NonameUntitled commented on modeling/models/bert4rec.py
> +            candidate_prefix,
Вообще я подумал, вроде бы я это реально выкручивал, так что можно убрать кандидатов и все, что с ними связяно

2024-09-09 13:51 UTC, NonameUntitled commented on modeling/models/bert4rec.py
> +        add_cls_token = True
Зачем ты выделяешь в переменную то, что используется только один раз?

2024-09-09 13:51 UTC, NonameUntitled commented on modeling/models/bert4rec.py
Та же ошибка, что и выше, надо не переписывать bert4rec, а сделать новый условно bet4rec_new

2024-09-09 13:51 UTC, NonameUntitled commented on modeling/models/bert4rec.py
> +            if '{}.ids'.format(self._candidate_prefix) in inputs: # only validation should be here
Да, я их убирал, так и должно быть, потом расскажу почему, а сейчас просто пойми, что валидация не нужна пока

2024-09-09 15:38 UTC, YaroslavZhurba commented on modeling/models/bert4rec.py
> +        self._cls_token = nn.Parameter(torch.rand(1, 1, embedding_dim))
окей, буду использовать squeeze, unsqueeze

2024-09-09 15:39 UTC, YaroslavZhurba commented on modeling/models/bert4rec.py
> +            if '{}.ids'.format(self._candidate_prefix) in inputs: # only validation should be here
разобрались, ненужно и убираем префиксы

2024-09-09 15:39 UTC, YaroslavZhurba commented on configs/train/bert4rec_train_config.json
> -    "type": "scientific",
окей, сделаю

2024-09-09 15:40 UTC, YaroslavZhurba commented on modeling/loss/base.py
> +        return cls(predictions_prefix=config.get('predictions_prefix'), candidates_prefix=config.get('candidates_prefix'))
тут ясно

2024-09-09 15:41 UTC, YaroslavZhurba commented on modeling/loss/base.py
> +        softmax_matrix = F.softmax(dot_product_matrix, dim=1)
окей, справлю

2024-09-09 15:41 UTC, YaroslavZhurba commented on modeling/models/base.py
> +    def _apply_sequential_encoder(self, events, lengths, add_cls_token = False):
pep8, проверить

2024-09-10 08:52 UTC, NonameUntitled requested changes

2024-09-10 08:52 UTC, NonameUntitled commented on .gitignore
> +data/Beauty/test.pkl
Можешь написать просто `data/*`

2024-09-10 08:52 UTC, NonameUntitled commented on modeling/models/bert4rec_cls.py
> +            candidate_prefix,
Мы же вчера обсуждали, что это больше не нужно

2024-09-10 08:52 UTC, NonameUntitled commented on modeling/models/bert4rec_cls.py
> +        self._candidate_prefix = candidate_prefix
И это не нужно

2024-09-10 08:52 UTC, NonameUntitled commented on modeling/models/bert4rec_cls.py
> +            candidate_prefix=config['candidate_prefix'],
И это не нужно

2024-09-10 08:52 UTC, NonameUntitled commented on modeling/models/bert4rec_cls.py
> +        self._cls_token = nn.Parameter(torch.rand(embedding_dim))
Это надо до `self._init_weights(initializer_range)` делать

2024-09-10 08:52 UTC, NonameUntitled commented on modeling/models/bert4rec_cls.py
> +                )  # (batch_size, num_candidates)
И это тоже надо убрать

2024-09-10 08:52 UTC, NonameUntitled commented on modeling/dataset/base.py
Отмени в этом файле все форматирования, которые ты сделал

2024-09-10 08:52 UTC, NonameUntitled commented on modeling/loss/base.py
> +        m = nn.LogSoftmax(dim=1)
что за `m`?

2024-09-10 14:56 UTC, YaroslavZhurba commented on modeling/dataset/base.py
>              validation_dataset[domain], validation_max_user_idx, validation_max_item_idx, validation_max_sequence_length = cls._create_dataset(
это что-то не получается венуть, думаю, что тут не принципиально

2024-09-10 14:58 UTC, YaroslavZhurba commented on modeling/dataset/base.py
>              validation_dataset[domain], validation_max_user_idx, validation_max_item_idx, validation_max_sequence_length = cls._create_dataset(
все эти пробелы/отступы в этой файле

2024-09-10 15:27 UTC, NonameUntitled approved these changes

2024-09-10 15:28 UTC, merged